### ISSUE TITLE
Stuck on "Installing GRUB bootloader for legacy PC booting support..."

### ISSUE THREAD

**Issue by Jojodicus** [WoeUSB/WoeUSB-ng#71]
similar to [#251](https://github.com/slacka/WoeUSB/issues/251) from the old repo, but still not reported here

## Issue Reproduce Instructions
Launch ``woeusbgui``, select ISO and USB-Stick, click install

## Expected Behavior
installation completed within reasonable time

## Current Behavior
stuck on "Installing GRUB bootloader for legacy PC booting support..." for a very long time (>30min), but completes successfully eventually.

### WoeUSB Version
0.2.10

### WoeUSB Source
[woeusb-ng](https://aur.archlinux.org/packages/woeusb-ng) from aur

### Information about the Operating System
EndeavourOS on 5.16.12-arch1-1

### Information about the Source Media
official Win10_21H2_German_x64.iso

### Information about the Target Device
[Intenso Speedline](https://www.intenso.de/en/products/usb-sticks/speed-line) 32GB

**Comment by WaxyMocha** [comment]
This was added in https://github.com/WoeUSB/WoeUSB-ng/pull/70, I just haven't pushed new release yet. You can install the woeusb-ng from source to get that functionality.

**Comment by niereklamuj** [comment]
The same problem there. Waited for 20 minutes already on "Installing Grub for legancy..."

**Comment by noloader** [comment]
We are still experiencing this issue with the latest release of woeusb-ng. The latest woeusb-ng is [v0.2.10](https://github.com/WoeUSB/WoeUSB-ng/releases/tag/v0.2.10).

Could you release a new version soon, please?

**Comment by daltroaugusto** [comment]
For me and all other people that still needs BIOS support, skipping GRUB2 Legacy step is not an option. What is exactly causing this bug?

**Comment by mruiz42** [comment]
also facing this issue on arch linux.
Here are the logs when running as root user. It seems to get stuck after the installing for i386 pc platform line. I am using x86_64 if that makes a difference. 

> umount: /media/woeusb_target_1666247380_886682: target is busy.
> umount: /media/woeusb_target_1666247380_886682: target is busy.
> /dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
> /dev/sdb: calling ioctl to re-read partition table: Success
> Cluster size has been automatically set to 4096 bytes.
> Creating NTFS volume structures.
> mkntfs completed successfully. Have a nice day.
> Installing for i386-pc platform.


`

**Comment by g-cyan** [comment]
I've been also encountering the problem of getting stuck on it with ubuntu 22.04.

**Comment by mruiz42** [comment]
@g-cyan that would depend. For the most part, most BIOS have switched to UEFI instead of tradtitional BIOS. So yeah, unless you explicitly set 'legacy only' in your BIOS, then legacy boot is not required. Especially since secure boot is now being adopted as a default on newer motherboards, UEFI should be supported. 

Another caveat I can think of, is if you wanted your windows install to be legacy for whatever reason, you would only be able to perform a UEFI windows install.

**Comment by flashpeter7** [comment]
same problem

**Comment by jarrisoncano** [comment]
Same problem

**Comment by flashpeter7** [comment]
> 
UPD:
i was needed to wait more.. and all went fine. about 10 mins

**Comment by JasonLandbridge** [comment]
For those coming here, canceling the "Installing GRUB boot-loader for legacy PC booting support..." step will still finish with a successful message. 

Before un-mounting, make sure to kill the "grub-install" process. After that, I could install windows 10 on a different PC without any problems

**Comment by SameIe** [comment]
> For those coming here, canceling the "Installing GRUB boot-loader for legacy PC booting support..." step will still finish with a successful message.
> 
> Before un-mounting, make sure to kill the "grub-install" process. After that, I could install windows 10 on a different PC without any problems
what about I wan to install in same PC? I need it right? because I want go back to Wins again.

**Comment by ZhiyuanChen** [comment]
> This was added in #70, I just haven't pushed new release yet. You can install the woeusb-ng from source to get that functionality.

I tried to install from source, still blocking. 
I can see it is blocking on installing for i386-pc platform

**Comment by ZhiyuanChen** [comment]
> The same problem there. Waited for 20 minutes already on "Installing Grub for legancy..."

It says Could not open Boot Directory: [10] Volume Corrupt

**Comment by mhicauber** [comment]
Had the same issue. Noticed it is referenced in the FAQ : https://github.com/WoeUSB/WoeUSB/wiki/F.A.Q., where they are  talking of up to 2 jours of waiting. Launching experiment now..

**Comment by mhicauber** [comment]
And I confirm process ends up successfully after a few hours.

**Comment by psi-4ward** [comment]
Confirmed, next day the process was finished and everything works

**Comment by hakabe** [comment]
The issue still presists. Why isn't there any option for user to disable legacy bios option? Make a tick-box until you get it this sorted out?

**Comment by mezhgano** [comment]
same problem, in my case i need legacy support so just waiting and waiting...

**Comment by psi-4ward** [comment]
Add a note so not every one has to Google. For me it's not a big case cause how often do we create an stick...

**Comment by bediu** [comment]
sooo.. nothing yet? anyone?

**Comment by SamiSuleiman** [comment]
I saw that someone said it took 2 hours and almost lost is. It finished after about 20 mins for me

**Comment by hontvari** [comment]
I just installed woeusb on ubuntu using the installation method recommended by woeusb (pip3) and the same thing happened,the gui is stuck for about 10 minutes.

**Comment by invictus2010** [comment]
why is this issue closed? i'm experiencing it as are other people

**Comment by bediu** [comment]
@invictus2010  I agree, this shouldn't be closed. There are some of us that had to wait over 1 hour without any UI indicator of what's happening.

**Comment by blauertee** [comment]
I don't believe that installing grub on a flash drive should take multiple hours. Its a few mb that have to be written. When the 6G windows image takes only a few minutes to be written. I bet there is a faster way to do this.

The whole of this has to be solved by the people who maintain `grub-install`. But you could only install minimal grub modules, maybe the compress option does something as well?

Also why is there no option like `--skip-legacy-boot`?

**Comment by devosalain** [comment]
https://github.com/WoeUSB/WoeUSB/wiki/F.A.Q.#why-does-the-drive-preparation-took-so-long-when-the---target-filesystem-is-set-to-ntfs

Going to sleep now. I'll have a look when i wake up  if it finished :)

**Comment by Jojodicus** [comment]
reporting back since it still seems to be a problem for a lot of users. since the issue stems from `grub-install` taking long on cheap pen-drives due to a lot of i/o (and getting it fixed upstream would involve lots of headaches), wouldn't a solution be to first generate the complete image for the stick on the main os disk (or even in ram) and then write that over? the install process itself is device-agnostic, so should work on non-device files as well

**Comment by devosalain** [comment]
After sometime (less then an hour), it finished without any error. Everything worked fine.
[Just a bit of patience is needed. I can live with it and am happy ]

**Comment by DownloadableFox** [comment]
Currently having this issue still after several hours. Was the flag to disable the legacy grub option ever introduced?

**Comment by ivelasquez-rl** [comment]
It happens to still getting stuck after 12 hours... No way this is normal.

**Comment by stevewells20** [comment]
Also an issue on Arch linux. Currently waiting 3 hours... At this moment it makes the software entirely unusable.

**Comment by recalderon** [comment]
Also an issue on ubuntu 22... woeusb's last edition available.

**Comment by SamiSuleiman** [comment]
@recalderon I'm curious, is there a reason to use woe over something like balena etcher?

**Comment by sebnapi** [comment]
Also having the issue with ubuntu 22.04 and 0.2.12

**Comment by recalderon** [comment]
> @recalderon I'm curious, is there a reason to use woe over something like balena etcher?

I tried to use balena before woeusb, but it gave me a warning about some boot config that windows image needs and they doesnt support right now....

**Comment by sebnapi** [comment]
Use Ventoy it just saved my day!

**Comment by ivelasquez-rl** [comment]
@sebnapi does it supports windows images?

**Comment by sebnapi** [comment]
Sure!

**Comment by isimons** [comment]
> Use Ventoy it just saved my day!

Thankyouuuuu!!!

**Comment by RizkiePratama** [comment]
Still getting this issue and it take me 2.5 Hours and still not Finished.
Not just it take too long, it making my system so slow as well. CPU and Memory usage are seems normal though.
After Canceling the process my system is running fast as normal again, not sure why.

```
Copied 5.2GiB from a total of 5.2GiB
/support/logging/en-us/actionqueueetw.dll.mui
Copied 5.2GiB from a total of 5.2GiBased with EFI support, applying workaround to make it support UEFI booting
99%
INFO: Detected existing EFI bootloader, workaround skipped.
Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform. <-- stuck on here
```

Tried Ventoy as sugested above and it worked like a charm for my Windows instalation. Thank You!

**Comment by bediu** [comment]
> Use Ventoy it just saved my day!

Shiny new bootable creator on the block

**Comment by alexcavadora** [comment]
Still getting this issue! using arch btw

**Comment by srgzx** [comment]
Same problem, Ubuntu Jammy...why is the issue closed...??

**Comment by srgzx** [comment]
So, this has been fixed in the WoeUSB-ng package -- you will have to manually install that and also use command line
Extremely annoying, but it works
https://github.com/WoeUSB/WoeUSB-ng
Command will look like 
sudo woeusb --target-filesystem NTFS --device ~/Downloads/Win11_23H2_English_x64v2.iso /dev/sda --workaround-skip-grub

**Comment by php4fan** [comment]
Issue still exists. Why is this closed?

BTW, I have interrupted the process while "installing GRUB for boot loader for legacy PC booting support...".

Will the usb stick just work on non-legacy PCs?

**Comment by srgzx** [comment]
> Will the usb stick just work on non-legacy PCs?

It didn't for me.  Grab the -ng version like I said, and it's not a problem.

**Comment by akumaburn** [comment]
Still happening.. I'm not even sure why this is necessary..

![Image](https://github.com/user-attachments/assets/f419cdf0-9789-4cd7-8f4d-032645ce4397)

**Comment by srgzx** [comment]
@akumaburn 

Please scroll up and see my comment.  You will need to manually install the NG version of WoeUSB, and then also alter the command you are using.  

Please post the exact command you are sending into your terminal.

Again, you will need to add to the end:
 
_--workaround-skip-grub_

And also again, this flag **ONLY WORKS** on the "NG" version of WoeUSB.  

Lastly, if anyone is trying to use this for Microsoft Windows 11 ISOs, don't bother.  It won't work.  Microsoft uses some weird ISO format where there's multiple partitions or something, and this can't make sense of that.  Can't remember the exact details.  I wasted so many hours on this, months ago.

**Comment by MaksatGalymzhan** [comment]
As the result shows, the program is not stuck it just works slowly. We need to wait a bit to complete the process.

**Comment by itoffshore** [comment]
> [@sebnapi](https://github.com/sebnapi) does it supports windows images?

with Ventoy (at least for Win11) - the data partition needs to be **NTFS** or you will hit error:

* `0x80070001 – 0x4002f` during installation under `wimboot` as the boot option (default boot method does not work) 

I've just successfully installed **Win11 IOT LTSC** from a Ventoy **NTFS** data partition `1`

When the Windows Installer asks you to sign in with an account / biometrics - remove the network cable & restart the pc. You will then be given the option to install a driver or "_I don't have internet_" & you can create a `local` account & [activate](https://massgrave.dev)

**Comment by SosthenesAlpha** [comment]
The process takes a while but eventually it works. If u are not booting for a legacy device, you might as well just cancel it. The files are already written in the flash drive anyway. 

NB: THIS WORKS ON UBUNTU LINUX. YOU CAN TRY OTHERS THOUGH.
